title: 'Asili'
description: 'ASILI is a collaborative design platform with social impact that guides collaborations between contemporary designers and East African artisans.'

url: 'http://asili.co'

link-instagram: 'https://www.instagram.com/asili.co/'
link-facebook: 'https://www.facebook.com/asili.co/'

color-background: '#e0dad3'
color-text: '#000000'
color-text-light: '#AAAAAA'
color-haiti: '#302D34'